dist: bionic

arch:
  - ppc64le
language: java
cache:
  directories:
    - travis_phantomjs
    - $HOME/.m2

before_install:
  # Upgrade PhantomJS to v2.1.1.
  - sudo apt-get install phantomjs
  - export QT_QPA_PLATFORM=offscreen
  
 

  
script:
  - travis_wait 50 mvn install


